#undef RT_THREAD_PRIORITY_MAX
#define RT_THREAD_PRIORITY_MAX 32
#undef IDLE_THREAD_STACK_SIZE
#define IDLE_THREAD_STACK_SIZE 1024
#undef RT_CONSOLEBUF_SIZE
#define RT_CONSOLEBUF_SIZE 256
#undef RT_DFS_ELM_DRIVES
#define RT_DFS_ELM_DRIVES 2
#undef RT_DFS_ELM_USE_LFN
#define RT_DFS_ELM_USE_LFN 3
#undef RT_DFS_ELM_MAX_SECTOR_SIZE
#define RT_DFS_ELM_MAX_SECTOR_SIZE 4096
#undef RT_LWIP_ETHTHREAD_PRIORITY
#define RT_LWIP_ETHTHREAD_PRIORITY 15
#undef CHECKSUM_CHECK_IP
#define CHECKSUM_CHECK_IP 0
#undef UTEST_THR_STACK_SIZE
#define UTEST_THR_STACK_SIZE 4096
#undef UTEST_THR_PRIORITY
#define UTEST_THR_PRIORITY 20
#undef PREFETCH_ENABLE
#define PREFETCH_ENABLE 0
#undef __FPU_USED
#define __FPU_USED 1
#undef __FPU_PRESENT
#define __FPU_PRESENT 0
#undef MULTIPLE
#define MULTIPLE 0
#undef USBH_KEEP_CFG_DESCRIPTOR
#define USBH_KEEP_CFG_DESCRIPTOR 1
#undef USBH_USE_OS
#define USBH_USE_OS 0
#undef NULL
#define NULL 0
#undef USBD_SUPPORT_USER_STRING
#define USBD_SUPPORT_USER_STRING 1
#undef USBD_SELF_POWERED
#define USBD_SELF_POWERED 1
#undef USBD_DEBUG_LEVEL
#define USBD_DEBUG_LEVEL 2
#undef USBD_DFU_MAX_ITF_NUM
#define USBD_DFU_MAX_ITF_NUM 1
#undef USED_RGB
#define USED_RGB 1
#undef SDIO_ENABLE
#define SDIO_ENABLE 1
#undef USBD_LPM_ENABLED
#define USBD_LPM_ENABLED 0
#undef UAVCAN_STM32_FREERTOS
#define UAVCAN_STM32_FREERTOS 0
#undef UAVCAN_STM32_BAREMETAL
#define UAVCAN_STM32_BAREMETAL 1
#undef FDCAN_NUM_IFACES
#define FDCAN_NUM_IFACES 1
#undef UCHAR_MAX
#define UCHAR_MAX 255
#undef USHRT_MAX
#define USHRT_MAX 65535
#undef UINT_MAX
#define UINT_MAX 4294967295
#undef ULONG_MAX
#define ULONG_MAX 4294967295
#undef __CMSIS_GENERIC
#define __CMSIS_GENERIC None
#undef MD5_H
#define MD5_H None
#undef SENSOR_POWER_GPIO
#define SENSOR_POWER_GPIO None
#undef RGB_R_GPIO
#define RGB_R_GPIO None
#undef RGB_G_GPIO
#define RGB_G_GPIO None
#undef RGB_B_GPIO
#define RGB_B_GPIO None
#undef FUM_CTRL_GPIO
#define FUM_CTRL_GPIO None
#undef USE_HAL_PCD_REGISTER_CALLBACKS
#define USE_HAL_PCD_REGISTER_CALLBACKS None
#undef STM32H7_DEV_ID
#define STM32H7_DEV_ID 1152
#undef TZ_PROCESS_STACK_SLOTS
#define TZ_PROCESS_STACK_SLOTS 8
#undef TZ_PROCESS_STACK_SIZE
#define TZ_PROCESS_STACK_SIZE 256
#undef TZ_START_NS
#define TZ_START_NS 2097152
#undef GTIM_IRQ_PRIORITY
#define GTIM_IRQ_PRIORITY 255
#undef USBD_SUPPORT_USER_STRING_DESC
#define USBD_SUPPORT_USER_STRING_DESC 0
#undef RT_SDIO_STACK_SIZE
#define RT_SDIO_STACK_SIZE 512
#undef RT_MMCSD_STACK_SIZE
#define RT_MMCSD_STACK_SIZE 1024
#undef RT_MMCSD_MAX_PARTITION
#define RT_MMCSD_MAX_PARTITION 16
#undef RT_SYSTEM_WORKQUEUE_STACKSIZE
#define RT_SYSTEM_WORKQUEUE_STACKSIZE 2048
#undef GTIM_IRQ_NUM
#define GTIM_IRQ_NUM None
#undef SysTick
#define SysTick None
#undef osCMSIS
#define osCMSIS None
#undef POWER_DOMAINS_NUMBER
#define POWER_DOMAINS_NUMBER None
#undef HAL_PCD_MODULE_ENABLED
#define HAL_PCD_MODULE_ENABLED None
#undef PRECISION
#define PRECISION 9
#undef YY_FLEX_SUBMINOR_VERSION
#define YY_FLEX_SUBMINOR_VERSION 1
#undef YY_BUF_SIZE
#define YY_BUF_SIZE 32768
#undef YY_NO_INPUT
#define YY_NO_INPUT 1
#undef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 16384
#undef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#undef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#undef YY_NULLPTR
#define YY_NULLPTR 0
#undef OLD_NCURSES
#define OLD_NCURSES 1
#undef HAL_CRC_MODULE_ENABLED
#define HAL_CRC_MODULE_ENABLED None
#undef HAL_TIM_MODULE_ENABLED
#define HAL_TIM_MODULE_ENABLED None
#undef HAL_DAC_MODULE_ENABLED
#define HAL_DAC_MODULE_ENABLED None
#undef HAL_I2S_MODULE_ENABLED
#define HAL_I2S_MODULE_ENABLED None
#undef HAL_SPI_MODULE_ENABLED
#define HAL_SPI_MODULE_ENABLED None
#undef HAL_ADC_MODULE_ENABLED
#define HAL_ADC_MODULE_ENABLED None
#undef HAL_WWDG_MODULE_ENABLED
#define HAL_WWDG_MODULE_ENABLED None
#undef HAL_CEC_MODULE_ENABLED
#define HAL_CEC_MODULE_ENABLED None
#undef ART_ACCLERATOR_ENABLE
#define ART_ACCLERATOR_ENABLE None
#undef HAL_SAI_MODULE_ENABLED
#define HAL_SAI_MODULE_ENABLED None
#undef SYSCLK_FREQ_HSE
#define SYSCLK_FREQ_HSE None
#undef yytext_ptr
#define yytext_ptr None
#undef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE None
#undef ECHO
#define ECHO None
#undef YY_DECL
#define YY_DECL None
#undef YY_BREAK
#define YY_BREAK None
#undef ACS_ULCORNER
#define ACS_ULCORNER None
#undef ACS_URCORNER
#define ACS_URCORNER None
#undef ACS_HLINE
#define ACS_HLINE None
#undef ACS_LTEE
#define ACS_LTEE None
#undef ACS_UARROW
#define ACS_UARROW None
#undef SD_DMA_MODE
#define SD_DMA_MODE None
#undef HAL_CAN_POOL_SIZE
#define HAL_CAN_POOL_SIZE 16000
#undef HAL_PERIPH_LOOP_DELAY_US
#define HAL_PERIPH_LOOP_DELAY_US 64
#undef HAL_CAN_DEFAULT_NODE_ID
#define HAL_CAN_DEFAULT_NODE_ID 10
#undef PRINTF_NTOA_BUFFER_SIZE
#define PRINTF_NTOA_BUFFER_SIZE 32
#undef PRINTF_FTOA_BUFFER_SIZE
#define PRINTF_FTOA_BUFFER_SIZE 32
#undef PRINTF_DEFAULT_FLOAT_PRECISION
#define PRINTF_DEFAULT_FLOAT_PRECISION 6
#undef UXR_CONFIG_UDP_TRANSPORT_MTU
#define UXR_CONFIG_UDP_TRANSPORT_MTU 0
#undef ARRAY_SIZE
#define ARRAY_SIZE 32
#undef CANARD_ENABLE_CANFD
#define CANARD_ENABLE_CANFD 0
#undef CANARD_MULTI_IFACE
#define CANARD_MULTI_IFACE 0
#undef CANARD_ENABLE_DEADLINE
#define CANARD_ENABLE_DEADLINE 0
#undef CANARD_ENABLE_TAO_OPTION
#define CANARD_ENABLE_TAO_OPTION 1
#undef CANARD_ALLOCATE_SEM
#define CANARD_ALLOCATE_SEM 0
#undef CANARD_64_BIT
#define CANARD_64_BIT 0
#undef CANARD_NUM_HANDLERS
#define CANARD_NUM_HANDLERS 3
#undef CANARD_IFACE_ALL
#define CANARD_IFACE_ALL 255
#undef CANARD_STM32_USE_CAN2
#define CANARD_STM32_USE_CAN2 0
#undef CANARD_STM32_DEBUG_INNER_PRIORITY_INVERSION
#define CANARD_STM32_DEBUG_INNER_PRIORITY_INVERSION 1
#undef CAN_RX_BUFFER_SIZE
#define CAN_RX_BUFFER_SIZE 16
#undef SUPPORT_FOR_AT90CAN__
#define SUPPORT_FOR_AT90CAN__ 1
#undef SUPPORT_FOR_SJA1000__
#define SUPPORT_FOR_SJA1000__ 1
#undef CMB_CPU_ARM_CORTEX_M0
#define CMB_CPU_ARM_CORTEX_M0 0
#undef CMB_CPU_ARM_CORTEX_M4
#define CMB_CPU_ARM_CORTEX_M4 2
#undef CMB_PRINT_LANGUAGE_ENGLISH
#define CMB_PRINT_LANGUAGE_ENGLISH 0
#undef MAVLINK_STACK_BUFFER
#define MAVLINK_STACK_BUFFER 0
#undef MAVLINK_COMM_NUM_BUFFERS
#define MAVLINK_COMM_NUM_BUFFERS 16
#undef MAVLINK_MAX_SIGNING_STREAMS
#define MAVLINK_MAX_SIGNING_STREAMS 16
#undef MAVLINK_COMMAND_24BIT
#define MAVLINK_COMMAND_24BIT 1
#undef MSD_USE_PRE_ERASED
#define MSD_USE_PRE_ERASED None
#undef PRINTF_MAX_FLOAT
#define PRINTF_MAX_FLOAT None
#undef NOINLINE_FUNC
#define NOINLINE_FUNC None
#undef CANARD_MALLOC
#define CANARD_MALLOC None
#undef CANARD_STM32_CAN_TIR_RTR
#define CANARD_STM32_CAN_TIR_RTR None
#undef CANARD_STM32_CAN_RIR_RTR
#define CANARD_STM32_CAN_RIR_RTR None
#undef CMB_PRINT_LANGUAGE
#define CMB_PRINT_LANGUAGE None
#undef CMB_CPU_PLATFORM_TYPE
#define CMB_CPU_PLATFORM_TYPE None
#undef MAVLINK_AVOID_GCC_STACK_BUG
#define MAVLINK_AVOID_GCC_STACK_BUG None
#undef MAVLINK_NEED_BYTE_SWAP
#define MAVLINK_NEED_BYTE_SWAP None
#undef MAVLINK_MAX_PAYLOAD_LEN
#define MAVLINK_MAX_PAYLOAD_LEN None
#undef MAVLINK_HELPER
#define MAVLINK_HELPER None
#undef MATRIX_GCC_4_8_WORKAROUND
#define MATRIX_GCC_4_8_WORKAROUND 0
#undef AIRFRAME
#define AIRFRAME 1
#undef MIN_SIZE
#define MIN_SIZE 24
#undef USE_FPU
#define USE_FPU 1
#undef RT_DEBUG_TIMER
#define RT_DEBUG_TIMER 0
#undef S_ISVTX
#define S_ISVTX 1000
#undef ZDEBUG
#define ZDEBUG 0
#undef LWIP_IPV4
#define LWIP_IPV4 1
#undef LWIP_IPV6
#define LWIP_IPV6 1
#undef NO_SYS
#define NO_SYS 0
#undef LWIP_SOCKET
#define LWIP_SOCKET 1
#undef LWIP_NETCONN
#define LWIP_NETCONN 1
#undef LWIP_IGMP
#define LWIP_IGMP 1
#undef LWIP_ICMP
#define LWIP_ICMP 1
#undef LWIP_SNMP
#define LWIP_SNMP 1
#undef LWIP_DNS
#define LWIP_DNS 1
#undef LWIP_HAVE_LOOPIF
#define LWIP_HAVE_LOOPIF 0
#undef LWIP_PLATFORM_BYTESWAP
#define LWIP_PLATFORM_BYTESWAP 0
#undef MEM_ALIGNMENT
#define MEM_ALIGNMENT 4
#undef MEMP_MEM_MALLOC
#define MEMP_MEM_MALLOC 0
#undef IP_NAT
#define IP_NAT 1
#undef LWIP_TCP
#define LWIP_TCP 1
#undef LWIP_ARP
#define LWIP_ARP 1
#undef ARP_QUEUEING
#define ARP_QUEUEING 1
#undef IP_FORWARD
#define IP_FORWARD 0
#undef IP_REASSEMBLY
#define IP_REASSEMBLY 1
#undef IP_FRAG
#define IP_FRAG 1
#undef LWIP_DHCP
#define LWIP_DHCP 1
#undef LWIP_AUTOIP
#define LWIP_AUTOIP 0
#undef LWIP_UDP
#define LWIP_UDP 1
#undef LWIP_UDPLITE
#define LWIP_UDPLITE 0
#undef LWIP_RAW
#define LWIP_RAW 1
#undef LWIP_STATS
#define LWIP_STATS 1
#undef LINK_STATS
#define LINK_STATS 1
#undef MEMP_STATS
#define MEMP_STATS 1
#undef PPPOE_SUPPORT
#define PPPOE_SUPPORT 1
#undef LWIP_NETIF_HOSTNAME
#define LWIP_NETIF_HOSTNAME 1
#undef LWIP_NETIF_API
#define LWIP_NETIF_API 1
#undef SO_REUSE
#define SO_REUSE 0
#undef MAKEFS_SUPPORT_DEFLATE
#define MAKEFS_SUPPORT_DEFLATE 0
#undef ALIGN_PAYLOAD
#define ALIGN_PAYLOAD 1
#undef SLIP_RX_FROM_ISR
#define SLIP_RX_FROM_ISR 0
#undef PPP_SUPPORT
#define PPP_SUPPORT 0
#undef LWIP_INCLUDED_POLARSSL_MD5
#define LWIP_INCLUDED_POLARSSL_MD5 1
#undef LWIP_INCLUDED_POLARSSL_MD4
#define LWIP_INCLUDED_POLARSSL_MD4 1
#undef LWIP_INCLUDED_POLARSSL_SHA1
#define LWIP_INCLUDED_POLARSSL_SHA1 1
#undef LWIP_INCLUDED_POLARSSL_DES
#define LWIP_INCLUDED_POLARSSL_DES 1
#undef LWIP_INCLUDED_POLARSSL_ARC4
#define LWIP_INCLUDED_POLARSSL_ARC4 1
#undef LWIP_CHKSUM_COPY_ALGORITHM
#define LWIP_CHKSUM_COPY_ALGORITHM 1
#undef LWIP_DEBUG_TIMERNAMES
#define LWIP_DEBUG_TIMERNAMES 0
#undef LWIP_TIMERS
#define LWIP_TIMERS 1
#undef LWIP_TCPIP_CORE_LOCKING
#define LWIP_TCPIP_CORE_LOCKING 1
#undef LWIP_TCPIP_CORE_LOCKING_INPUT
#define LWIP_TCPIP_CORE_LOCKING_INPUT 0
#undef MEM_LIBC_MALLOC
#define MEM_LIBC_MALLOC 0
#undef MEMP_OVERFLOW_CHECK
#define MEMP_OVERFLOW_CHECK 0
#undef MEMP_SANITY_CHECK
#define MEMP_SANITY_CHECK 0
#undef MEM_USE_POOLS
#define MEM_USE_POOLS 0
#undef MEMP_USE_CUSTOM_POOLS
#define MEMP_USE_CUSTOM_POOLS 0
#undef MEMP_NUM_UDP_PCB
#define MEMP_NUM_UDP_PCB 4
#undef MEMP_NUM_ARP_QUEUE
#define MEMP_NUM_ARP_QUEUE 30
#undef MEMP_NUM_IGMP_GROUP
#define MEMP_NUM_IGMP_GROUP 8
#undef ETHARP_SUPPORT_STATIC_ENTRIES
#define ETHARP_SUPPORT_STATIC_ENTRIES 0
#undef IP_OPTIONS_ALLOWED
#define IP_OPTIONS_ALLOWED 1
#undef DNS_LOCAL_HOSTLIST
#define DNS_LOCAL_HOSTLIST 0
#undef DNS_LOCAL_HOSTLIST_IS_DYNAMIC
#define DNS_LOCAL_HOSTLIST_IS_DYNAMIC 0
#undef TCP_OOSEQ_MAX_BYTES
#define TCP_OOSEQ_MAX_BYTES 0
#undef TCP_OOSEQ_MAX_PBUFS
#define TCP_OOSEQ_MAX_PBUFS 0
#undef TCP_LISTEN_BACKLOG
#define TCP_LISTEN_BACKLOG 0
#undef TCP_DEFAULT_LISTEN_BACKLOG
#define TCP_DEFAULT_LISTEN_BACKLOG 255
#undef LWIP_TCP_TIMESTAMPS
#define LWIP_TCP_TIMESTAMPS 0
#undef LWIP_EVENT_API
#define LWIP_EVENT_API 0
#undef LWIP_CALLBACK_API
#define LWIP_CALLBACK_API 1
#undef LWIP_WND_SCALE
#define LWIP_WND_SCALE 0
#undef LWIP_NETIF_STATUS_CALLBACK
#define LWIP_NETIF_STATUS_CALLBACK 0
#undef LWIP_NETIF_LINK_CALLBACK
#define LWIP_NETIF_LINK_CALLBACK 0
#undef LWIP_NETIF_REMOVE_CALLBACK
#define LWIP_NETIF_REMOVE_CALLBACK 0
#undef LWIP_NETIF_HWADDRHINT
#define LWIP_NETIF_HWADDRHINT 0
#undef LWIP_NUM_NETIF_CLIENT_DATA
#define LWIP_NUM_NETIF_CLIENT_DATA 0
#undef LWIP_TCPIP_TIMEOUT
#define LWIP_TCPIP_TIMEOUT 0
#undef LWIP_NETCONN_SEM_PER_THREAD
#define LWIP_NETCONN_SEM_PER_THREAD 0
#undef LWIP_CHECKSUM_ON_COPY
#define LWIP_CHECKSUM_ON_COPY 0
#undef LWIP_IPV6_SEND_ROUTER_SOLICIT
#define LWIP_IPV6_SEND_ROUTER_SOLICIT 1
#undef LWIP_IPV6_DHCP6
#define LWIP_IPV6_DHCP6 0
#undef M_PI
#define M_PI None
#undef CONFIG_SYS_CLK_FREQ
#define CONFIG_SYS_CLK_FREQ None
#undef XPSEUDO_ASM_GCC_H
#define XPSEUDO_ASM_GCC_H None
#undef XREG_CORTEXR5_H
#define XREG_CORTEXR5_H None
#undef _BUS_IN_THRD_PRIO
#define _BUS_IN_THRD_PRIO None
#undef EOVERFLOW
#define EOVERFLOW None
#undef LWP_MEM_PAGE_SIZE
#define LWP_MEM_PAGE_SIZE None
#undef LWP_MEM_MAX_PAGE_COUNT
#define LWP_MEM_MAX_PAGE_COUNT None
#undef UAC_USE_FEATURE_UNIT
#define UAC_USE_FEATURE_UNIT None
#undef MIN
#define MIN None
#undef SFUD_FLASH_DEVICE_TABLE
#define SFUD_FLASH_DEVICE_TABLE None
#undef DHCP_SERVER_PORT
#define DHCP_SERVER_PORT 67
#undef FS_FILE_FLAGS_HEADER_INCLUDED
#define FS_FILE_FLAGS_HEADER_INCLUDED 1
#undef LWIP_HTTPD_TIMING
#define LWIP_HTTPD_TIMING 0
#undef LWIP_HTTPD_CUSTOM_FILES
#define LWIP_HTTPD_CUSTOM_FILES 0
#undef LWIP_HTTPD_DYNAMIC_FILE_READ
#define LWIP_HTTPD_DYNAMIC_FILE_READ 0
#undef HTTPD_PRECALCULATED_CHECKSUM
#define HTTPD_PRECALCULATED_CHECKSUM 0
#undef LWIP_HTTPD_FS_ASYNC_READ
#define LWIP_HTTPD_FS_ASYNC_READ 0
#undef LWIP_MDNS_RESPONDER
#define LWIP_MDNS_RESPONDER 0
#undef SNMP_TRAP_DESTINATIONS
#define SNMP_TRAP_DESTINATIONS 1
#undef MEMP_SANITY_REGION_BEFORE_ALIGNED
#define MEMP_SANITY_REGION_BEFORE_ALIGNED 0
#undef MEMP_SANITY_REGION_AFTER_ALIGNED
#define MEMP_SANITY_REGION_AFTER_ALIGNED 0
#undef LWIP_DISABLE_TCP_SANITY_CHECKS
#define LWIP_DISABLE_TCP_SANITY_CHECKS 0
#undef LWIP_CHKSUM_ALGORITHM
#define LWIP_CHKSUM_ALGORITHM 2
#undef LWIP_INLINE_IP_CHKSUM
#define LWIP_INLINE_IP_CHKSUM 0
#undef CHECKSUM_GEN_IP_INLINE
#define CHECKSUM_GEN_IP_INLINE 1
#undef IP_ACCEPT_LINK_LAYER_ADDRESSING
#define IP_ACCEPT_LINK_LAYER_ADDRESSING 1
#undef SLIP_MAX_SIZE
#define SLIP_MAX_SIZE 1500
#undef TCP_SND_QUEUELEN
#define TCP_SND_QUEUELEN 40
#undef CHECK_SEGMENTS_ON_OOSEQ
#define CHECK_SEGMENTS_ON_OOSEQ 1
#undef UIP_FIXEDADDR
#define UIP_FIXEDADDR 0
#undef UIP_PINGADDRCONF
#define UIP_PINGADDRCONF 0
#undef UIP_FIXEDETHADDR
#define UIP_FIXEDETHADDR 0
#undef UIP_REASSEMBLY
#define UIP_REASSEMBLY 0
#undef UIP_UDP
#define UIP_UDP 0
#undef UIP_UDP_CHECKSUMS
#define UIP_UDP_CHECKSUMS 0
#undef UIP_ACTIVE_OPEN
#define UIP_ACTIVE_OPEN 1
#undef UIP_URGDATA
#define UIP_URGDATA 0
#undef UIP_STATISTICS
#define UIP_STATISTICS 0
#undef UIP_LOGGING
#define UIP_LOGGING 0
#undef UIP_BROADCAST
#define UIP_BROADCAST 0
#undef HTTPD_FS_STATISTICS
#define HTTPD_FS_STATISTICS 1
#undef FSDATA_FILE_ALIGNMENT
#define FSDATA_FILE_ALIGNMENT 0
#undef MEM_OVERFLOW_CHECK
#define MEM_OVERFLOW_CHECK 0
#undef LWIP_TCP_SACK_OUT
#define LWIP_TCP_SACK_OUT 0
#undef LWIP_TCP_MAX_SACK_NUM
#define LWIP_TCP_MAX_SACK_NUM 4
#undef LWIP_ALTCP
#define LWIP_ALTCP 0
#undef LWIP_SINGLE_NETIF
#define LWIP_SINGLE_NETIF 0
#undef LWIP_NETIF_EXT_STATUS_CALLBACK
#define LWIP_NETIF_EXT_STATUS_CALLBACK 0
#undef HTTPD_ENABLE_HTTPS
#define HTTPD_ENABLE_HTTPS 0
#undef TCP_OVERSIZE
#define TCP_OVERSIZE 1
#undef NO_SYS_NO_TIMERS
#define NO_SYS_NO_TIMERS 0
#undef MEMP_SEPARATE_POOLS
#define MEMP_SEPARATE_POOLS 0
#undef LWIP_HAVE_SLIPIF
#define LWIP_HAVE_SLIPIF 0
#undef DHCPD_CLIENT_IP_MIN
#define DHCPD_CLIENT_IP_MIN 2
#undef MAC_ADDR_LEN
#define MAC_ADDR_LEN 6
#undef MAC_TABLE_LEN
#define MAC_TABLE_LEN 4
#undef FF_FS_MINIMIZE
#define FF_FS_MINIMIZE 0
#undef FF_USE_STRFUNC
#define FF_USE_STRFUNC 0
#undef FF_USE_FIND
#define FF_USE_FIND 0
#undef FF_USE_FASTSEEK
#define FF_USE_FASTSEEK 1
#undef FF_USE_EXPAND
#define FF_USE_EXPAND 0
#undef FF_USE_CHMOD
#define FF_USE_CHMOD 0
#undef FF_USE_LABEL
#define FF_USE_LABEL 0
#undef FF_USE_FORWARD
#define FF_USE_FORWARD 0
#undef FF_CODE_PAGE
#define FF_CODE_PAGE 936
#undef FF_FS_RPATH
#define FF_FS_RPATH 0
#undef FF_VOLUMES
#define FF_VOLUMES 1
#undef FF_STR_VOLUME_ID
#define FF_STR_VOLUME_ID 0
#undef FF_MULTI_PARTITION
#define FF_MULTI_PARTITION 0
#undef FF_MIN_SS
#define FF_MIN_SS 512
#undef FF_LBA64
#define FF_LBA64 0
#undef FF_USE_TRIM
#define FF_USE_TRIM 0
#undef FF_FS_TINY
#define FF_FS_TINY 0
#undef FF_FS_EXFAT
#define FF_FS_EXFAT 1
#undef FF_FS_NORTC
#define FF_FS_NORTC 0
#undef FF_FS_NOFSINFO
#define FF_FS_NOFSINFO 0
#undef FF_FS_LOCK
#define FF_FS_LOCK 0
#undef _RPC_TYPES_H
#define _RPC_TYPES_H 1
#undef _RPC_RPC_H
#define _RPC_RPC_H 1
#undef _RPC_CLNT_H
#define _RPC_CLNT_H 1
#undef _RPC_MSG_H
#define _RPC_MSG_H 1
#undef TOO_FAR
#define TOO_FAR 4096
#undef Z_BUFSIZE
#define Z_BUFSIZE 16384
#undef MIN_MATCH
#define MIN_MATCH 3
#undef CYGNUM_FS_JFFS2_RAW_NODE_REF_CACHE_POOL_SIZE
#define CYGNUM_FS_JFFS2_RAW_NODE_REF_CACHE_POOL_SIZE 0
#undef CONFIG_USE_STATIC_MEMORY_ALLOCATOR
#define CONFIG_USE_STATIC_MEMORY_ALLOCATOR 0
#undef CONFIG_USE_SYSTEM_MEMORY_ALLOCATOR
#define CONFIG_USE_SYSTEM_MEMORY_ALLOCATOR 1
#undef BYTE_ORDER
#define BYTE_ORDER None
#undef LWIP_HOOK_FILENAME
#define LWIP_HOOK_FILENAME None
#undef ENABLE_LOOPBACK
#define ENABLE_LOOPBACK None
#undef LWIP_ETHERNET
#define LWIP_ETHERNET None
#undef LWIP_SUPPORT_CUSTOM_PBUF
#define LWIP_SUPPORT_CUSTOM_PBUF None
#undef LWIP_MULTICAST_TX_OPTIONS
#define LWIP_MULTICAST_TX_OPTIONS None
#undef LWIP_PPP_API
#define LWIP_PPP_API None
#undef SO_REUSEADDR
#define SO_REUSEADDR None
#undef SO_BROADCAST
#define SO_BROADCAST None
#undef LWIP_IPV6_REASS
#define LWIP_IPV6_REASS None
#undef LWIP_CHKSUM
#define LWIP_CHKSUM None
#undef LWIP_ICMP6
#define LWIP_ICMP6 None
#undef SLIP_USE_RX_THREAD
#define SLIP_USE_RX_THREAD None
#undef TCP_SND_BUF
#define TCP_SND_BUF None
#undef LWIP_IPV6_ADDRESS_LIFETIMES
#define LWIP_IPV6_ADDRESS_LIFETIMES None
#undef LWIP_IPV6_AUTOCONFIG
#define LWIP_IPV6_AUTOCONFIG None
#undef PBUF_POOL_BUFSIZE
#define PBUF_POOL_BUFSIZE None
#undef NUM_SOCKETS
#define NUM_SOCKETS None
#undef LWIP_VERSION
#define LWIP_VERSION None
#undef TCP_WND
#define TCP_WND None
#undef SO_ACCEPTCONN
#define SO_ACCEPTCONN None
#undef SO_KEEPALIVE
#define SO_KEEPALIVE None
#undef SO_LINGER
#define SO_LINGER None
#undef IP_OPTIONS_SEND
#define IP_OPTIONS_SEND None
#undef IP_DEBUG
#define IP_DEBUG None
#undef LOG_TAG
#define LOG_TAG None
#undef DHCPD_SERVER_IP
#define DHCPD_SERVER_IP None
#undef FF_DEFINED
#define FF_DEFINED None
#undef FF_FS_REENTRANT
#define FF_FS_REENTRANT None
#undef FF_MAX_SS
#define FF_MAX_SS None
#undef FF_USE_LFN
#define FF_USE_LFN None
#undef DEVICE_PART_MAX
#define DEVICE_PART_MAX None
#undef STDC
#define STDC None
#undef GZ_SUFFIX
#define GZ_SUFFIX None
#undef ESPIPE
#define ESPIPE None
#undef __ECOS
#define __ECOS None
#undef CYGOPT_FS_JFFS2_WRITE
#define CYGOPT_FS_JFFS2_WRITE None
#undef RTTHREAD_VERSION
#define RTTHREAD_VERSION None
#undef RT_CONFIG_UFFS_ECC_MODE
#define RT_CONFIG_UFFS_ECC_MODE None
#undef UFFS_ECC_NONE
#define UFFS_ECC_NONE None
#undef UFFS_FEMU_ENABLE_INJECTION
#define UFFS_FEMU_ENABLE_INJECTION None
