#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #108 */

/* ConfigFuzz: MAVLINK_ENABLED_CSAIRLINK */
#ifdef MAVLINK_ENABLED_CSAIRLINK
#undef MAVLINK_ENABLED_CSAIRLINK
#endif
#define MAVLINK_ENABLED_CSAIRLINK 0

/* ConfigFuzz: AP_MAVLINK_MSG_RC_CHANNELS_RAW_ENABLED */
#ifdef AP_MAVLINK_MSG_RC_CHANNELS_RAW_ENABLED
#undef AP_MAVLINK_MSG_RC_CHANNELS_RAW_ENABLED
#endif
#define AP_MAVLINK_MSG_RC_CHANNELS_RAW_ENABLED 1

/* ConfigFuzz: HAL_USB_PRODUCT_ID */
#ifdef HAL_USB_PRODUCT_ID
#undef HAL_USB_PRODUCT_ID
#endif
#define HAL_USB_PRODUCT_ID 1

/* ConfigFuzz: HAL_RCOUT_RGBLED_GREEN */
#ifdef HAL_RCOUT_RGBLED_GREEN
#undef HAL_RCOUT_RGBLED_GREEN
#endif
#define HAL_RCOUT_RGBLED_GREEN 0

/* ConfigFuzz: HAL_GENERATOR_ENABLED */
#ifdef HAL_GENERATOR_ENABLED
#undef HAL_GENERATOR_ENABLED
#endif
#define HAL_GENERATOR_ENABLED 1

/* ConfigFuzz: HAL_WITH_DRONECAN */
#ifdef HAL_WITH_DRONECAN
#undef HAL_WITH_DRONECAN
#endif
#define HAL_WITH_DRONECAN 0

/* ConfigFuzz: HAL_GPIO_INPUT */
#ifdef HAL_GPIO_INPUT
#undef HAL_GPIO_INPUT
#endif
#define HAL_GPIO_INPUT 1

/* ConfigFuzz: MAVLINK_ENABLED_UALBERTA */
#ifdef MAVLINK_ENABLED_UALBERTA
#undef MAVLINK_ENABLED_UALBERTA
#endif
#define MAVLINK_ENABLED_UALBERTA 1

/* ConfigFuzz: AP_HAL_SHARED_DMA_ENABLED */
#ifdef AP_HAL_SHARED_DMA_ENABLED
#undef AP_HAL_SHARED_DMA_ENABLED
#endif
#define AP_HAL_SHARED_DMA_ENABLED 0

#endif /* _AP_CONFIG_H_ */
