#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #34 */

/* ConfigFuzz: MAVLINK_MSG_ID_AP_ADC */
#ifdef MAVLINK_MSG_ID_AP_ADC
#undef MAVLINK_MSG_ID_AP_ADC
#endif
#define MAVLINK_MSG_ID_AP_ADC 1

/* ConfigFuzz: MODE_CIRCLE_ENABLED */
#ifdef MODE_CIRCLE_ENABLED
#undef MODE_CIRCLE_ENABLED
#endif
#define MODE_CIRCLE_ENABLED 0

/* ConfigFuzz: HAL_WITH_IO_MCU */
#ifdef HAL_WITH_IO_MCU
#undef HAL_WITH_IO_MCU
#endif
#define HAL_WITH_IO_MCU 1

/* ConfigFuzz: HAL_DSHOT_ENABLED */
#ifdef HAL_DSHOT_ENABLED
#undef HAL_DSHOT_ENABLED
#endif
#define HAL_DSHOT_ENABLED 1

/* ConfigFuzz: MAVLINK_ENABLED_ICAROUS */
#ifdef MAVLINK_ENABLED_ICAROUS
#undef MAVLINK_ENABLED_ICAROUS
#endif
#define MAVLINK_ENABLED_ICAROUS 0

/* ConfigFuzz: CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED */
#ifdef CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED
#undef CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED
#endif
#define CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED 0

/* ConfigFuzz: METADATA_MAX_i */
#ifdef METADATA_MAX_i
#undef METADATA_MAX_i
#endif
#define METADATA_MAX_i 32

/* ConfigFuzz: FS_GCS_ENABLED_ALWAYS_LAND */
#ifdef FS_GCS_ENABLED_ALWAYS_LAND
#undef FS_GCS_ENABLED_ALWAYS_LAND
#endif
#define FS_GCS_ENABLED_ALWAYS_LAND 1

/* ConfigFuzz: MAVLINK_MSG_ID_WIFI_CONFIG_AP_CRC */
#ifdef MAVLINK_MSG_ID_WIFI_CONFIG_AP_CRC
#undef MAVLINK_MSG_ID_WIFI_CONFIG_AP_CRC
#endif
#define MAVLINK_MSG_ID_WIFI_CONFIG_AP_CRC 0

/* ConfigFuzz: ESC_CHANNEL_MAP_RUNNING_DIRECTION */
#ifdef ESC_CHANNEL_MAP_RUNNING_DIRECTION
#undef ESC_CHANNEL_MAP_RUNNING_DIRECTION
#endif
#define ESC_CHANNEL_MAP_RUNNING_DIRECTION 0

#endif /* _AP_CONFIG_H_ */
