#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #185 */

/* ConfigFuzz: HAL_COMPASS_AUTO_ROT_DEFAULT */
#ifdef HAL_COMPASS_AUTO_ROT_DEFAULT
#undef HAL_COMPASS_AUTO_ROT_DEFAULT
#endif
#define HAL_COMPASS_AUTO_ROT_DEFAULT 0

/* ConfigFuzz: AP_SRV_CHANNELS_ENABLED */
#ifdef AP_SRV_CHANNELS_ENABLED
#undef AP_SRV_CHANNELS_ENABLED
#endif
#define AP_SRV_CHANNELS_ENABLED 0

/* ConfigFuzz: AP_COPTER_AHRS_AUTO_TRIM_ENABLED */
#ifdef AP_COPTER_AHRS_AUTO_TRIM_ENABLED
#undef AP_COPTER_AHRS_AUTO_TRIM_ENABLED
#endif
#define AP_COPTER_AHRS_AUTO_TRIM_ENABLED 0

/* ConfigFuzz: CONFIG_LWIP_PPP_SUPPORT */
#ifdef CONFIG_LWIP_PPP_SUPPORT
#undef CONFIG_LWIP_PPP_SUPPORT
#endif
#define CONFIG_LWIP_PPP_SUPPORT 0

/* ConfigFuzz: HAL_NUM_CAN_IFACES */
#ifdef HAL_NUM_CAN_IFACES
#undef HAL_NUM_CAN_IFACES
#endif
#define HAL_NUM_CAN_IFACES 0

/* ConfigFuzz: HAL_RCOUT_RGBLED_GREEN */
#ifdef HAL_RCOUT_RGBLED_GREEN
#undef HAL_RCOUT_RGBLED_GREEN
#endif
#define HAL_RCOUT_RGBLED_GREEN 0

/* ConfigFuzz: MODE_DRIFT_ENABLED */
#ifdef MODE_DRIFT_ENABLED
#undef MODE_DRIFT_ENABLED
#endif
#define MODE_DRIFT_ENABLED 0

#endif /* _AP_CONFIG_H_ */
