#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #515 */

/* ConfigFuzz: HAL_FLASH_PROTECTION */
#ifdef HAL_FLASH_PROTECTION
#undef HAL_FLASH_PROTECTION
#endif
#define HAL_FLASH_PROTECTION 0

/* ConfigFuzz: MAVLINK_MSG_ID_AP_ADC */
#ifdef MAVLINK_MSG_ID_AP_ADC
#undef MAVLINK_MSG_ID_AP_ADC
#endif
#define MAVLINK_MSG_ID_AP_ADC 1

/* ConfigFuzz: HAL_IMUHEAT_P_DEFAULT */
#ifdef HAL_IMUHEAT_P_DEFAULT
#undef HAL_IMUHEAT_P_DEFAULT
#endif
#define HAL_IMUHEAT_P_DEFAULT 0

/* ConfigFuzz: TELEM_TIME_SLOT_MAX */
#ifdef TELEM_TIME_SLOT_MAX
#undef TELEM_TIME_SLOT_MAX
#endif
#define TELEM_TIME_SLOT_MAX 4

/* ConfigFuzz: HAL_USE_HW_RNG */
#ifdef HAL_USE_HW_RNG
#undef HAL_USE_HW_RNG
#endif
#define HAL_USE_HW_RNG 1

/* ConfigFuzz: AP_SERIALMANAGER_ENABLED */
#ifdef AP_SERIALMANAGER_ENABLED
#undef AP_SERIALMANAGER_ENABLED
#endif
#define AP_SERIALMANAGER_ENABLED 1

/* ConfigFuzz: AP_MISSION_ENABLED */
#ifdef AP_MISSION_ENABLED
#undef AP_MISSION_ENABLED
#endif
#define AP_MISSION_ENABLED 1

/* ConfigFuzz: MAX_PWMS */
#ifdef MAX_PWMS
#undef MAX_PWMS
#endif
#define MAX_PWMS 2

/* ConfigFuzz: AP_SRV_CHANNELS_ENABLED */
#ifdef AP_SRV_CHANNELS_ENABLED
#undef AP_SRV_CHANNELS_ENABLED
#endif
#define AP_SRV_CHANNELS_ENABLED 1

/* ConfigFuzz: FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_LAND */
#ifdef FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_LAND
#undef FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_LAND
#endif
#define FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_LAND 1

#endif /* _AP_CONFIG_H_ */
