#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #790 */

/* ConfigFuzz: MAVLINK_ENABLED_STANDARD */
#ifdef MAVLINK_ENABLED_STANDARD
#undef MAVLINK_ENABLED_STANDARD
#endif
#define MAVLINK_ENABLED_STANDARD 1

/* ConfigFuzz: AP_SOCKET_NATIVE_ENABLED */
#ifdef AP_SOCKET_NATIVE_ENABLED
#undef AP_SOCKET_NATIVE_ENABLED
#endif
#define AP_SOCKET_NATIVE_ENABLED 1

/* ConfigFuzz: AP_SRV_CHANNELS_ENABLED */
#ifdef AP_SRV_CHANNELS_ENABLED
#undef AP_SRV_CHANNELS_ENABLED
#endif
#define AP_SRV_CHANNELS_ENABLED 0

/* ConfigFuzz: MODE_ZIGZAG_ENABLED */
#ifdef MODE_ZIGZAG_ENABLED
#undef MODE_ZIGZAG_ENABLED
#endif
#define MODE_ZIGZAG_ENABLED 1

/* ConfigFuzz: HAL_DSHOT_ENABLED */
#ifdef HAL_DSHOT_ENABLED
#undef HAL_DSHOT_ENABLED
#endif
#define HAL_DSHOT_ENABLED 0

/* ConfigFuzz: HAL_RALLY_ENABLED */
#ifdef HAL_RALLY_ENABLED
#undef HAL_RALLY_ENABLED
#endif
#define HAL_RALLY_ENABLED 0

/* ConfigFuzz: FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_RTL */
#ifdef FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_RTL
#undef FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_RTL
#endif
#define FS_THR_ENABLED_ALWAYS_SMARTRTL_OR_RTL 0

/* ConfigFuzz: HAL_INS_RATE_LOOP */
#ifdef HAL_INS_RATE_LOOP
#undef HAL_INS_RATE_LOOP
#endif
#define HAL_INS_RATE_LOOP 1

/* ConfigFuzz: HAL_BARO_EXTERNAL_BUS_DEFAULT */
#ifdef HAL_BARO_EXTERNAL_BUS_DEFAULT
#undef HAL_BARO_EXTERNAL_BUS_DEFAULT
#endif
#define HAL_BARO_EXTERNAL_BUS_DEFAULT 1

#endif /* _AP_CONFIG_H_ */
