#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #391 */

/* ConfigFuzz: MAVLINK_ENABLED_CSAIRLINK */
#ifdef MAVLINK_ENABLED_CSAIRLINK
#undef MAVLINK_ENABLED_CSAIRLINK
#endif
#define MAVLINK_ENABLED_CSAIRLINK 1

/* ConfigFuzz: HAVE_ENUM_GIMBAL_DEVICE_CAP_FLAGS */
#ifdef HAVE_ENUM_GIMBAL_DEVICE_CAP_FLAGS
#undef HAVE_ENUM_GIMBAL_DEVICE_CAP_FLAGS
#endif
#define HAVE_ENUM_GIMBAL_DEVICE_CAP_FLAGS 0

/* ConfigFuzz: MAVLINK_ENABLED_LOWEHEISER */
#ifdef MAVLINK_ENABLED_LOWEHEISER
#undef MAVLINK_ENABLED_LOWEHEISER
#endif
#define MAVLINK_ENABLED_LOWEHEISER 1

/* ConfigFuzz: HAL_SEMAPHORE_BLOCK_FOREVER */
#ifdef HAL_SEMAPHORE_BLOCK_FOREVER
#undef HAL_SEMAPHORE_BLOCK_FOREVER
#endif
#define HAL_SEMAPHORE_BLOCK_FOREVER 1

/* ConfigFuzz: FS_GCS_ENABLED_ALWAYS_SMARTRTL_OR_LAND */
#ifdef FS_GCS_ENABLED_ALWAYS_SMARTRTL_OR_LAND
#undef FS_GCS_ENABLED_ALWAYS_SMARTRTL_OR_LAND
#endif
#define FS_GCS_ENABLED_ALWAYS_SMARTRTL_OR_LAND 1

/* ConfigFuzz: AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN */
#ifdef AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN
#undef AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN
#endif
#define AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN 1

/* ConfigFuzz: HAL_BATT_CURR_PIN */
#ifdef HAL_BATT_CURR_PIN
#undef HAL_BATT_CURR_PIN
#endif
#define HAL_BATT_CURR_PIN 0

/* ConfigFuzz: RANGEFINDER_MAX_INSTANCES */
#ifdef RANGEFINDER_MAX_INSTANCES
#undef RANGEFINDER_MAX_INSTANCES
#endif
#define RANGEFINDER_MAX_INSTANCES 4

/* ConfigFuzz: FS_GCS_ENABLED_BRAKE_OR_LAND */
#ifdef FS_GCS_ENABLED_BRAKE_OR_LAND
#undef FS_GCS_ENABLED_BRAKE_OR_LAND
#endif
#define FS_GCS_ENABLED_BRAKE_OR_LAND 1

/* ConfigFuzz: FS_THR_ENABLED_BRAKE_OR_LAND */
#ifdef FS_THR_ENABLED_BRAKE_OR_LAND
#undef FS_THR_ENABLED_BRAKE_OR_LAND
#endif
#define FS_THR_ENABLED_BRAKE_OR_LAND 0

#endif /* _AP_CONFIG_H_ */
