#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #20 */

/* ConfigFuzz: HAL_AIRSPEED_TYPE_DEFAULT */
#ifdef HAL_AIRSPEED_TYPE_DEFAULT
#undef HAL_AIRSPEED_TYPE_DEFAULT
#endif
#define HAL_AIRSPEED_TYPE_DEFAULT 1

/* ConfigFuzz: HAL_GPIO_LED_ON */
#ifdef HAL_GPIO_LED_ON
#undef HAL_GPIO_LED_ON
#endif
#define HAL_GPIO_LED_ON 1

/* ConfigFuzz: BENCH_DEFINE_MAP_PERMUTATION */
#ifdef BENCH_DEFINE_MAP_PERMUTATION
#undef BENCH_DEFINE_MAP_PERMUTATION
#endif
#define BENCH_DEFINE_MAP_PERMUTATION 1

/* ConfigFuzz: AC_PRECLAND_ENABLED */
#ifdef AC_PRECLAND_ENABLED
#undef AC_PRECLAND_ENABLED
#endif
#define AC_PRECLAND_ENABLED 1

/* ConfigFuzz: MAVLINK_ENABLED_AVSSUAS */
#ifdef MAVLINK_ENABLED_AVSSUAS
#undef MAVLINK_ENABLED_AVSSUAS
#endif
#define MAVLINK_ENABLED_AVSSUAS 0

/* ConfigFuzz: AP_RANGEFINDER_MAVLINK_TIMEOUT_MS */
#ifdef AP_RANGEFINDER_MAVLINK_TIMEOUT_MS
#undef AP_RANGEFINDER_MAVLINK_TIMEOUT_MS
#endif
#define AP_RANGEFINDER_MAVLINK_TIMEOUT_MS 0

/* ConfigFuzz: MODE_SMARTRTL_ENABLED */
#ifdef MODE_SMARTRTL_ENABLED
#undef MODE_SMARTRTL_ENABLED
#endif
#define MODE_SMARTRTL_ENABLED 0

/* ConfigFuzz: MAVLINK_ENABLED_COMMON */
#ifdef MAVLINK_ENABLED_COMMON
#undef MAVLINK_ENABLED_COMMON
#endif
#define MAVLINK_ENABLED_COMMON 0

/* ConfigFuzz: AP_MODULE_SUPPORTED */
#ifdef AP_MODULE_SUPPORTED
#undef AP_MODULE_SUPPORTED
#endif
#define AP_MODULE_SUPPORTED 0

/* ConfigFuzz: AP_RANGEFINDER_LUA_TIMEOUT_MS */
#ifdef AP_RANGEFINDER_LUA_TIMEOUT_MS
#undef AP_RANGEFINDER_LUA_TIMEOUT_MS
#endif
#define AP_RANGEFINDER_LUA_TIMEOUT_MS 0

#endif /* _AP_CONFIG_H_ */
