#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #62 */

/* ConfigFuzz: BENCH_DEFINE_MAP_PERMUTATION */
#ifdef BENCH_DEFINE_MAP_PERMUTATION
#undef BENCH_DEFINE_MAP_PERMUTATION
#endif
#define BENCH_DEFINE_MAP_PERMUTATION 0

/* ConfigFuzz: AP_NOTIFY_RCOUTPUTRGBLEDINVERTED_LED_ENABLED */
#ifdef AP_NOTIFY_RCOUTPUTRGBLEDINVERTED_LED_ENABLED
#undef AP_NOTIFY_RCOUTPUTRGBLEDINVERTED_LED_ENABLED
#endif
#define AP_NOTIFY_RCOUTPUTRGBLEDINVERTED_LED_ENABLED 1

/* ConfigFuzz: LEDDARONE_DETECTIONS_MAX */
#ifdef LEDDARONE_DETECTIONS_MAX
#undef LEDDARONE_DETECTIONS_MAX
#endif
#define LEDDARONE_DETECTIONS_MAX 1

/* ConfigFuzz: MAVLINK_ENABLED_UALBERTA */
#ifdef MAVLINK_ENABLED_UALBERTA
#undef MAVLINK_ENABLED_UALBERTA
#endif
#define MAVLINK_ENABLED_UALBERTA 0

/* ConfigFuzz: HAL_DEFAULT_INS_FAST_SAMPLE */
#ifdef HAL_DEFAULT_INS_FAST_SAMPLE
#undef HAL_DEFAULT_INS_FAST_SAMPLE
#endif
#define HAL_DEFAULT_INS_FAST_SAMPLE 0

/* ConfigFuzz: AP_COMPASS_OFFSETS_MAX_DEFAULT */
#ifdef AP_COMPASS_OFFSETS_MAX_DEFAULT
#undef AP_COMPASS_OFFSETS_MAX_DEFAULT
#endif
#define AP_COMPASS_OFFSETS_MAX_DEFAULT 1

#endif /* _AP_CONFIG_H_ */
