#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #118 */

/* ConfigFuzz: AP_DEVO_TELEM_ENABLED */
#ifdef AP_DEVO_TELEM_ENABLED
#undef AP_DEVO_TELEM_ENABLED
#endif
#define AP_DEVO_TELEM_ENABLED 1

/* ConfigFuzz: BACKEND_SAMPLE_RATE_MAX */
#ifdef BACKEND_SAMPLE_RATE_MAX
#undef BACKEND_SAMPLE_RATE_MAX
#endif
#define BACKEND_SAMPLE_RATE_MAX 4

/* ConfigFuzz: AC_PRECLAND_ENABLED */
#ifdef AC_PRECLAND_ENABLED
#undef AC_PRECLAND_ENABLED
#endif
#define AC_PRECLAND_ENABLED 1

/* ConfigFuzz: HAL_INS_NONE */
#ifdef HAL_INS_NONE
#undef HAL_INS_NONE
#endif
#define HAL_INS_NONE 1

/* ConfigFuzz: AC_MAVLINK_SOLO_BUTTON_COMMAND_HANDLING_ENABLED */
#ifdef AC_MAVLINK_SOLO_BUTTON_COMMAND_HANDLING_ENABLED
#undef AC_MAVLINK_SOLO_BUTTON_COMMAND_HANDLING_ENABLED
#endif
#define AC_MAVLINK_SOLO_BUTTON_COMMAND_HANDLING_ENABLED 0

#endif /* _AP_CONFIG_H_ */
