#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #109 */

/* ConfigFuzz: AP_PERIPH_BARO_ENABLED */
#ifdef AP_PERIPH_BARO_ENABLED
#undef AP_PERIPH_BARO_ENABLED
#endif
#define AP_PERIPH_BARO_ENABLED 1

/* ConfigFuzz: AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED */
#ifdef AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
#undef AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
#endif
#define AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED 1

/* ConfigFuzz: HAL_INS_HIGHRES_SAMPLE */
#ifdef HAL_INS_HIGHRES_SAMPLE
#undef HAL_INS_HIGHRES_SAMPLE
#endif
#define HAL_INS_HIGHRES_SAMPLE 0

/* ConfigFuzz: AP_DEVO_TELEM_ENABLED */
#ifdef AP_DEVO_TELEM_ENABLED
#undef AP_DEVO_TELEM_ENABLED
#endif
#define AP_DEVO_TELEM_ENABLED 1

/* ConfigFuzz: BENCH_DEFINE_MAP_EXPLICIT */
#ifdef BENCH_DEFINE_MAP_EXPLICIT
#undef BENCH_DEFINE_MAP_EXPLICIT
#endif
#define BENCH_DEFINE_MAP_EXPLICIT 0

/* ConfigFuzz: CONFIG_LWIP_DHCP_RESTORE_LAST_IP */
#ifdef CONFIG_LWIP_DHCP_RESTORE_LAST_IP
#undef CONFIG_LWIP_DHCP_RESTORE_LAST_IP
#endif
#define CONFIG_LWIP_DHCP_RESTORE_LAST_IP 0

/* ConfigFuzz: MPUREG_CONFIG_EXT_SYNC_GY */
#ifdef MPUREG_CONFIG_EXT_SYNC_GY
#undef MPUREG_CONFIG_EXT_SYNC_GY
#endif
#define MPUREG_CONFIG_EXT_SYNC_GY 0

/* ConfigFuzz: HAL_SEMAPHORE_BLOCK_FOREVER */
#ifdef HAL_SEMAPHORE_BLOCK_FOREVER
#undef HAL_SEMAPHORE_BLOCK_FOREVER
#endif
#define HAL_SEMAPHORE_BLOCK_FOREVER 0

#endif /* _AP_CONFIG_H_ */
