#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #90 */

/* ConfigFuzz: BACKEND_SAMPLE_RATE_MAX */
#ifdef BACKEND_SAMPLE_RATE_MAX
#undef BACKEND_SAMPLE_RATE_MAX
#endif
#define BACKEND_SAMPLE_RATE_MAX 4

/* ConfigFuzz: HAL_SPRAYER_ENABLED */
#ifdef HAL_SPRAYER_ENABLED
#undef HAL_SPRAYER_ENABLED
#endif
#define HAL_SPRAYER_ENABLED 0

/* ConfigFuzz: AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED */
#ifdef AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
#undef AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
#endif
#define AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED 0

/* ConfigFuzz: MODE_CIRCLE_ENABLED */
#ifdef MODE_CIRCLE_ENABLED
#undef MODE_CIRCLE_ENABLED
#endif
#define MODE_CIRCLE_ENABLED 0

/* ConfigFuzz: FSYNC_CONFIG_EXT_SYNC_AX */
#ifdef FSYNC_CONFIG_EXT_SYNC_AX
#undef FSYNC_CONFIG_EXT_SYNC_AX
#endif
#define FSYNC_CONFIG_EXT_SYNC_AX 1

/* ConfigFuzz: AP_FEATURE_SBUS_OUT */
#ifdef AP_FEATURE_SBUS_OUT
#undef AP_FEATURE_SBUS_OUT
#endif
#define AP_FEATURE_SBUS_OUT 1

/* ConfigFuzz: RPM_MAX_INSTANCES */
#ifdef RPM_MAX_INSTANCES
#undef RPM_MAX_INSTANCES
#endif
#define RPM_MAX_INSTANCES 16

#endif /* _AP_CONFIG_H_ */
