#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #25 */

/* ConfigFuzz: BENCH_DEFINE_MAP_OVERRIDE */
#ifdef BENCH_DEFINE_MAP_OVERRIDE
#undef BENCH_DEFINE_MAP_OVERRIDE
#endif
#define BENCH_DEFINE_MAP_OVERRIDE 1

/* ConfigFuzz: HAL_INS_TRIM_LIMIT_DEG */
#ifdef HAL_INS_TRIM_LIMIT_DEG
#undef HAL_INS_TRIM_LIMIT_DEG
#endif
#define HAL_INS_TRIM_LIMIT_DEG 1

/* ConfigFuzz: MPUREG_CONFIG_EXT_SYNC_AZ */
#ifdef MPUREG_CONFIG_EXT_SYNC_AZ
#undef MPUREG_CONFIG_EXT_SYNC_AZ
#endif
#define MPUREG_CONFIG_EXT_SYNC_AZ 0

/* ConfigFuzz: HAL_DISABLE_ADC_DRIVER */
#ifdef HAL_DISABLE_ADC_DRIVER
#undef HAL_DISABLE_ADC_DRIVER
#endif
#define HAL_DISABLE_ADC_DRIVER 0

/* ConfigFuzz: HAL_WITH_IO_MCU_BIDIR_DSHOT */
#ifdef HAL_WITH_IO_MCU_BIDIR_DSHOT
#undef HAL_WITH_IO_MCU_BIDIR_DSHOT
#endif
#define HAL_WITH_IO_MCU_BIDIR_DSHOT 1

/* ConfigFuzz: AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN */
#ifdef AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN
#undef AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN
#endif
#define AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN 1

/* ConfigFuzz: HAL_GPIO_OUTPUT */
#ifdef HAL_GPIO_OUTPUT
#undef HAL_GPIO_OUTPUT
#endif
#define HAL_GPIO_OUTPUT 0

/* ConfigFuzz: AP_NETWORKING_BACKEND_PPP */
#ifdef AP_NETWORKING_BACKEND_PPP
#undef AP_NETWORKING_BACKEND_PPP
#endif
#define AP_NETWORKING_BACKEND_PPP 1

/* ConfigFuzz: MAVLINK_MSG_ID_PARAM_MAP_RC_CRC */
#ifdef MAVLINK_MSG_ID_PARAM_MAP_RC_CRC
#undef MAVLINK_MSG_ID_PARAM_MAP_RC_CRC
#endif
#define MAVLINK_MSG_ID_PARAM_MAP_RC_CRC 1

#endif /* _AP_CONFIG_H_ */
