#pragma once
/* ConfigFuzz generated configuration */

#ifndef _AP_CONFIG_H_
#define _AP_CONFIG_H_

/* Essential defines */
#define _GNU_SOURCE 1
#define WAF_BUILD 1
#define PYTHONDIR "/usr/lib/python3/dist-packages"
#define PYTHONARCHDIR "/usr/lib/python3/dist-packages"
#define __STDC_FORMAT_MACROS 1
#define AP_SIGNED_FIRMWARE 0
#define HAVE_CMATH_ISFINITE 1
#define HAVE_CMATH_ISINF 1
#define HAVE_CMATH_ISNAN 1
#define NEED_CMATH_ISFINITE_STD_NAMESPACE 1
#define NEED_CMATH_ISINF_STD_NAMESPACE 1
#define NEED_CMATH_ISNAN_STD_NAMESPACE 1

/* ConfigFuzz Test #131 */

/* ConfigFuzz: AP_PERIPH_BATTERY_BALANCE_ENABLED */
#ifdef AP_PERIPH_BATTERY_BALANCE_ENABLED
#undef AP_PERIPH_BATTERY_BALANCE_ENABLED
#endif
#define AP_PERIPH_BATTERY_BALANCE_ENABLED 1

/* ConfigFuzz: AP_SCHEDULER_ENABLED */
#ifdef AP_SCHEDULER_ENABLED
#undef AP_SCHEDULER_ENABLED
#endif
#define AP_SCHEDULER_ENABLED 0

/* ConfigFuzz: AP_MAVLINK_COMMAND_LONG_ENABLED */
#ifdef AP_MAVLINK_COMMAND_LONG_ENABLED
#undef AP_MAVLINK_COMMAND_LONG_ENABLED
#endif
#define AP_MAVLINK_COMMAND_LONG_ENABLED 1

/* ConfigFuzz: AP_PERIPH_RCIN_ENABLED */
#ifdef AP_PERIPH_RCIN_ENABLED
#undef AP_PERIPH_RCIN_ENABLED
#endif
#define AP_PERIPH_RCIN_ENABLED 1

/* ConfigFuzz: AP_PERIPH_RANGEFINDER_ENABLED */
#ifdef AP_PERIPH_RANGEFINDER_ENABLED
#undef AP_PERIPH_RANGEFINDER_ENABLED
#endif
#define AP_PERIPH_RANGEFINDER_ENABLED 1

/* ConfigFuzz: HAL_BARO_NONE */
#ifdef HAL_BARO_NONE
#undef HAL_BARO_NONE
#endif
#define HAL_BARO_NONE 1

/* ConfigFuzz: WEATHERVANE_ENABLED */
#ifdef WEATHERVANE_ENABLED
#undef WEATHERVANE_ENABLED
#endif
#define WEATHERVANE_ENABLED 0

/* ConfigFuzz: HAL_QUADPLANE_ENABLED */
#ifdef HAL_QUADPLANE_ENABLED
#undef HAL_QUADPLANE_ENABLED
#endif
#define HAL_QUADPLANE_ENABLED 0

/* ConfigFuzz: BENCH_DEFINE_MAP_PERMUTATION */
#ifdef BENCH_DEFINE_MAP_PERMUTATION
#undef BENCH_DEFINE_MAP_PERMUTATION
#endif
#define BENCH_DEFINE_MAP_PERMUTATION 1

#endif /* _AP_CONFIG_H_ */
